name: gopeed_api
description: A dart project provide Gopeed downloader Rest API interacting.
version: 1.0.4
repository: https://github.com/yzyf1312/gopeed_api

topics:
 - http
 - network
 - protocols
 - gopeed
 - download

environment:
  sdk: ^3.5.3

dependencies:
  http: ^1.2.2

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
